Lost.UI/Controllers/RedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Lost.Model.Common;
using Lost.Service.Common;
using Lost.DAL;
using System.Net;
using System.Data;
using PagedList;
using System.Threading.Tasks;
using Lost.Common.Filters;
using Lost.UI.Models;
using Lost.Model;

namespace Lost.UI.Controllers
{
    public class RedController : Controller
    {
        private readonly IRedService Service;

        public RedController(IRedService service)
        {
            Service = service;
        }

        public async Task<ActionResult> Index(string searchString, string currentFilter, int pageNumber = 0, int pageSize = 0)
        {
            var rc = await Service.GetAllAsync(new GenericFilter(searchString, pageNumber, pageSize));
            return View(rc);
        }

        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(RedCrossModel rcm)
        {
            if (ModelState.IsValid)
            {
                await Service.AddAsync(AutoMapper.Mapper.Map<RedCross>(rcm));

                return RedirectToAction("Index");
            }
            return View(rcm);
        }

        public async Task<ActionResult> Delete(Guid id)
        {
            var rcToDelete = await Service.GetByIdAsync(id);
            if (rcToDelete == null)
                return HttpNotFound();

            return View(rcToDelete);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteRedCross(Guid id)
        {
            await Service.DeleteAsync(id);
            return RedirectToAction("Index");
        }
    }
}

Lost.UI/Controllers/UserController.cs
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Threading.Tasks;
using System.Threading;
using System.Net;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using System.Web.Security;
using Lost.Service.Common;
using Lost.DAL.Models;
using Lost.UI.Models;
using Lost.Model.Common;
using Lost.DAL;

namespace Lost.UI.Controllers
{
    public class UserController : Controller
    {
        protected IUserService Service { get; private set; }
        protected IRedService RedService { get; private set; }
        public RoleManager<IdentityRole> RoleManager { get; private set; }
        protected UserManager<ApplicationUserEntity> UserManager { get; private set; }

        public UserController(IUserService service, IRedService redService, RoleManager<IdentityRole> roleManager)
        {
            Service = service;
            RedService = redService;
            RoleManager = roleManager;
            UserManager = new UserManager<ApplicationUserEntity>(new UserStore<ApplicationUserEntity>(new SearchContext()));
        }

        // GET: User
        
        public async Task<ActionResult> Index(ApplicationUserEntity user)
        {
            return View(await UserManager.Users.ToListAsync());
        }

        [AllowAnonymous]
        public async Task<ActionResult> Create()
        {
            ViewBag.RedCross = await RedService.GetAllAsync(null);
            return View();
        }
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(RegisterViewModel model, ApplicationUserModel user)
        {
            if (ModelState.IsValid)
            {
                //http://prntscr.com/9q077y
                user = new ApplicationUserModel { Id = user.Id, UserName=model.UserName, Email = model.Email, FirstName = model.FirstName, LastName = model.LastName, OIB = model.OIB, RedCrossId = model.RedCrossId };

                //Register new user: http://prntscr.com/9q0bo6
                await Service.RegisterUser(AutoMapper.Mapper.Map<IApplicationUser>(user), model.Password);

                return RedirectToAction("Index");

            }
            else
            {
                ViewBag.RedCross = await RedService.GetAllAsync(null);
                return View();
            }
        }

        public async Task<ActionResult> Edit(string userId)
        {
            if (userId == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var user = await UserManager.FindByIdAsync(userId);

            if (user == null) return HttpNotFound();

            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(ApplicationUserModel editUser, string userId, string roleId)
        {
            if (userId == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var user = await UserManager.FindByIdAsync(userId);
            user.UserName = editUser.UserName;
            if (ModelState.IsValid)
            {
                await UserManager.UpdateAsync(user);

                var rolesForUser = await UserManager.GetRolesAsync(userId);
                if (rolesForUser.Count() > 0)
                {
                    foreach (var item in rolesForUser)
                    {
                        var result = await UserManager.RemoveFromRoleAsync(userId, item);
                    }
                }

                if (!String.IsNullOrWhiteSpace(roleId))
                {
                    var role = await RoleManager.FindByIdAsync(roleId);

                    var result = await UserManager.AddToRoleAsync(userId, role.Name);
                    if (!result.Succeeded)
                    {
                        ModelState.AddModelError("", result.Errors.First().ToString());
                        return View();
                    }
                }
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }

        public async Task<ActionResult> Delete(string id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var user = await UserManager.FindByIdAsync(id);

            if (user == null) return HttpNotFound();

            return View(user);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteUser(string id)
        {
            var user = await UserManager.FindByIdAsync(id);
            await UserManager.DeleteAsync(user);
            return RedirectToAction("Index");
        }
    }
}

Lost.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Lost in Europe</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Lost", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Missing", "Index", "Lost")</li>
                    <li>@Html.ActionLink("Red Cross", "Index", "Red")</li>
                    <li>@Html.ActionLink("User pages", "Index", "User")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Lost.UI/Views/Shared/_Login.cshtml
@using Lost.UI.Models
@model LoginViewModel

@{
    ViewBag.Title = "LOGIN";
}

<div class="titleLine">
    <h3>@ViewBag.Title</h3>
    <hr />
</div>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            @using (Html.BeginForm("Login", "Account", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @*@Html.LabelFor(m => m.UserName, new { @class = "col-md-2 control-label" })*@
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.UserName, new { @class = "form-control", placeholder = "User Name" })
                        @Html.ValidationMessageFor(m => m.UserName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @*@Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })*@
                    <div class="col-md-10">
                        @Html.PasswordFor(m => m.Password, new { @class = "form-control", placeholder = "Password" })
                        @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.CheckBoxFor(m => m.RememberMe)
                            @Html.LabelFor(m => m.RememberMe)
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-10">
                        <input type="submit" value="Log in" class="btn btn-primary" />
                    </div>
                </div>
            }
        </section>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}