Lost.UI/Controllers/LostController.cs
using Lost.Common;
using Lost.DAL;
using Lost.Model;
using Lost.Model.Common;
using Lost.Service.Common;
using Lost.UI.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Lost.UI.Controllers
{
    public class LostController : Controller
    {
        
        protected ILostService LostService { get; private set; }
        protected IRedService RedService { get; private set; }

        #region Constructor
        public LostController(ILostService lostService, IRedService redService)
        {
            LostService = lostService;
            RedService = redService;
        }
        #endregion

        #region methods
        public async Task<ActionResult> Index(string searchString, string currentFilter, int pageNumber = 0, int pageSize = 0)
        {
            var lp = await LostService.GetAllLostPersons(new Common.Filters.GenericFilter(searchString, pageNumber, pageSize));
            return View(lp);
        }


        public async Task<ActionResult> ReportMissing()
        {
            ViewBag.RedCross = await RedService.GetAllAsync(null);

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ReportMissing([Bind(Include="Id,FirstName,LastName,Birthday,City,Country,DateLastSeen,LocationLastSeen,ReporterName,ReportDate,Location,IsFound,RedCrossId")] LostPersonModel lpm)
        {
            if (ModelState.IsValid)
            {

                await LostService.ReportLostPerson(AutoMapper.Mapper.Map<LostPerson>(lpm));
                
                return RedirectToAction("Index");
            }
            ViewBag.RedCross = await RedService.GetAllAsync(null);

            return View(lpm);
        }

        public async Task<ActionResult> Details(Guid id)
        {
            try
            {
                if (id == null) 
                { 
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                ILostPerson lp = await LostService.FindByIdAsync(id);

                if (lp == null)
                    return HttpNotFound();

                return View(lp);
            }
            catch(Exception ex)
            {
                throw ex;
            }
        }
        public async Task<ActionResult> Edit(Guid id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            ViewBag.RedCross = await RedService.GetAllAsync(null);

            ILostPerson lostPerson = await LostService.FindByIdAsync(id);
            if (lostPerson == null)
                return HttpNotFound();

            return View(lostPerson);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,FirstName,LastName,Birthday,City,Country,DateLastSeen,LocationLastSeen,ReporterName,ReportDate,Location,IsFound,RedCrossId")] LostPersonModel lpm)
        {
            try
            {
                ViewBag.RedCross = await RedService.GetAllAsync(null);

                if (ModelState.IsValid)
                {
                    await LostService.UpdateLostPerson(AutoMapper.Mapper.Map<LostPerson>(lpm));
                    return RedirectToAction("Index");
                }

                return View();
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public async Task<ActionResult> Delete(Guid id) //must be nullable
        {
            //if (id == null)
            //    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var lostPersonToDelete = await LostService.FindByIdAsync(id);
            if (lostPersonToDelete == null)
                return HttpNotFound();

            return View(lostPersonToDelete);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeletePost(Guid id)
        {
            await LostService.DeleteMissingPerson(id);
            return RedirectToAction("Index");
        }

    }
        #endregion
}

Lost.UI/Views/Lost/Delete.cshtml
@model Lost.Model.Common.ILostPerson

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>LostPersonEntity</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Birthday)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Birthday)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateLastSeen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateLastSeen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LocationLastSeen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LocationLastSeen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReporterName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReporterName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReportDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReportDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsFound)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsFound)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RedCrossId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RedCrossId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Lost.UI/Views/Lost/Details.cshtml
@model Lost.Model.Common.ILostPerson

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>LostPersonEntity</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Birthday)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Birthday)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateLastSeen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateLastSeen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LocationLastSeen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LocationLastSeen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReporterName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReporterName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReportDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReportDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsFound)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsFound)
        </dd>

        <dt>
            TREBA IZBACITI: @Html.DisplayNameFor(model => model.RedCrossId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RedCrossId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Lost.UI/Views/Lost/Edit.cshtml
@model Lost.Model.Common.ILostPerson

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>LostPersonEntity</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div> 
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Birthday, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Birthday, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Birthday, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateLastSeen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateLastSeen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateLastSeen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LocationLastSeen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LocationLastSeen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LocationLastSeen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReporterName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReporterName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReporterName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReportDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReportDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReportDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsFound, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsFound)
                    @Html.ValidationMessageFor(model => model.IsFound, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RedCrossId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.RedCrossId, new SelectList(ViewBag.RedCross, "RedCrossId", "Name"), "Select RC")
                @Html.ValidationMessageFor(model => model.RedCrossId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Lost.UI/Views/Lost/Index.cshtml
<!--model IEnumerable<Lost.Model.Common.ILostPerson>-->
@model PagedList.IPagedList<Lost.Model.Common.ILostPerson>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Missing";
}

<h2>Missing persons</h2>

<p>
    @Html.ActionLink("Report Missing Person", "ReportMissing", "Lost")
</p>
@using (Html.BeginForm("Index", "Lost", FormMethod.Get))
{
    <p>
        <span>@Html.TextBox("searchString", null, new { @class = "form-control", placeholder="Search" })</span>
        <input type="submit" value="Search" class="btn btn-default" />
    </p>
}
<table class="table">
    <tr>
        <th>
            First name
        </th>
        <th>
            Last Name
        </th>
        <th>
            Location last seen
        </th>
        <th>
            Date last seen
        </th>
        <th>
            Report date
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(model => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(model => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(model => item.LocationLastSeen)
            </td>
            <td>
                @Html.DisplayFor(model => item.DateLastSeen)
            </td>
            <td>
                @Html.DisplayFor(model => item.ReportDate)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>

        </tr>
    }
</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
@Html.PagedListPager(Model, pageNumber => Url.Action("Index", new { pageNumber }));

Lost.UI/Views/Lost/ReportMissing.cshtml
@model Lost.Model.LostPerson
@{
    ViewBag.Title = "ReportMissing";
}

<h2>Report Missing</h2>


@using (Html.BeginForm("ReportMissing", "Lost")) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Report missing person</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Birthday, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Birthday, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Birthday, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateLastSeen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateLastSeen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateLastSeen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LocationLastSeen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LocationLastSeen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LocationLastSeen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReporterName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReporterName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReporterName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReportDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReportDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReportDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.IsFound, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsFound)
                    @Html.ValidationMessageFor(model => model.IsFound, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <!--DROPDOWNLISTFOR za dohvacanje RC-ova iz baze-->
        <div class="form-group">
            @Html.LabelFor(model => model.RedCrossId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.RedCrossId, new SelectList(ViewBag.RedCross, "RedCrossId", "Name"), "Select RC")
                @Html.ValidationMessageFor(model => model.RedCrossId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Report" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}